// <auto-generated />
using System;
using AdultMult.DataProvider;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AdultMult.Migrations
{
    [DbContext(typeof(AdultMultContext))]
    [Migration("20200822143158_RemoveRedundantColumns")]
    partial class RemoveRedundantColumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AdultMult.Models.Mult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("IsUpdated")
                        .HasColumnName("updated")
                        .HasColumnType("boolean");

                    b.Property<string>("RussianCaption")
                        .IsRequired()
                        .HasColumnName("russiancaption")
                        .HasColumnType("text");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnName("series")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnName("updatedate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("mults");
                });
#pragma warning restore 612, 618
        }
    }
}
